---
language: ruby
bundler_args: --without development --path=~/.bundle
rvm:
  - 1.9.3
env:
  global:
    - secure: "dYThxgC+wL1Teoa43IFqG2Gv9umzBZjmy3jDdH1D29O5u6ekY5k0AF4i5bDq\nOgAMFR/FIeqwVajNsn60/qn287BR4LuamTssjGP3FnUnvuDEFxDFBNz+KwBd\nF+9ryZRwNrWVDOxHt8KaoOSgXFiP522K3uBkz7JvFm63jj0Zw5g="
    - secure: "IL5x5UL21pyP+dvSGwyHzx9Dvua8aBnpVexTSScUvCbb/m7VhrfftfQYpDee\nQcNAbcM7OFdrPokg3RhPGwMwBsMXedkFE6sLOH8tml6IGWgOmGemV8E7LmzL\nadxpMilgxdKsYgVwi6WZ+mt5LdM0prlW5NabZTmMHaosDyBGERg="
    - secure: "H8HnHZjxhvEuZ2LRI012i2Y2PKRJqRbA6nuJaK0nkLjviFjEe+KNB6rsuosd\nWcVYqxJP0mb6JjKrwCmeAgCyE4swy4p1slC6Er0wpMEQ+ndseCAUWhUO5RLL\n+wHP1Bfu0u8qoMdSOWRnPg8Q1boE8kM71xQ0oLdRo9X600ZjU5I="
    - secure: "biE7FXW01hxze4qEIEs+8lUhNYdVkRViGsEJpyiRs/XIM75/TfPZ7fdiGxXr\nDAL0Sbfj+jI6PY0h7sjPVZVpuJwG69A9Rk+WJuFD2qVcInLhdcL1xMX+vtHM\nr2/X5Oa889LUGMxcj7qxB6I8S8PPIoEWlZ6sZ9mqAlmwYkd5gS4="
    - secure: "jjPuVaXLYUzYRdWkKo9e+vxMe5ioCh9aLOcs2Z9DR7ofqNU0ELEGjYkEWj3Z\nwiXoRMY4dizfT4SnGr5xX4VhWajVLFCSetjLI6JWN9WftOU9WQz9WnEepiju\nE/StLX6rbQ0DfsdHpPKf2+BYYxatn0PCNaQv55UNVfV427GUL2U=" #pass
    - secure: "TEaAO9iaINS3Z/3JijfCaVsSuhv010E/MwDMy46ZAhW2ljQXOVfrC/72Oe5xdqfGg5VOW6PMkS/iUW0N+dprBFw5k/ZFkz4qlsIOncRz0pj+PQOLo8IMyFa3U0HDgCIjcM7YdF+AQ6z/lVDxR6cbmDKrKru+P46xQuwNBFFQ5+k=" #ip
    - secure: "LbZST+jfw92UVwz05BL5t3NrxHefHyrKmi4P0nh0MnYXlkgMLq1/jLX3a2nB\nywe4rq0v1qNaSFH1DpeRtEBb/HFfo7VA7gUdbmLgz/hR02r7+cWTwFD7vBCT\nz2vWZX8u/53HrIDiT6Ic0yxDBpDdnmpgd1jBr93tdrXmPEgCu1A="
    - BUNDLE_ARCHIVE="travis_challenges_bundle"
  matrix:
    - DB=postgres
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
  - "chmod 777 script/travis/bundle_install.sh"
  - "chmod 777 script/travis/send_files.sh"
  - "./script/travis/bundle_install.sh"
after_script:
  - "ruby script/travis/bundle_cache.rb"
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate RAILS_ENV=test
  - mkdir tmp
  - mkdir tmp/cache
  - phantomjs --version
script:
  - echo $TEST_ENV
  - bundle exec rake test_with_coveralls RAILS_ENV=test
notifications:
  email: false
  hipchat:
    - secure: "MdDty16B6vKD5G7Q036uO/yiWpGcdhoC43FfVrjfdsi5MQrviTPEXrexHP/4\ny1Ut3q14zU3XvwMDxz3sWIlHDG16D1djfILPVGHiQGJWtnVRYpIm0Ug5ZZqO\naDs3UvK8QbPOkeAhMIN98grKDv9x4NpkN8aVHbYkIqyyBGf1IO8="
