---
language: ruby
rvm:
- 1.9.3
env:
- secure: "LTShr15xa9PEn1dxAWM2uMCYxjaBEHkUuAIU1JeYxfYfLwf73xpRZXjj++9q\nxdgIWg6OtJX75n06X82APXKAAncd+zvO1ov0QBleDh4OA+I0CpX3ZmwSjWvM\nu+KOvASmftstILV0Hjddx1RLcdlETlJxrKbIvM9A1z427TcPibY="
- secure: "VzxMIZCw5/JzGlTNDAuAgUmY6BTkHha3yQCVNre9h4B5miSAp/NhHBwTwrw2\ng7om6GtDWyJrlBQna9zPSJsfhzds3bGRjghEXOm4tMaOTTGmPxWbyRjYhiLC\nM3IJcwH/LUJcpPwHemVFANunWv+z8HKveQWoaXjZvfBF3ACXwhE="
- secure: "d0G3bIS+c3Qhz+3CZhV0lkf4vVh8ue/FCuZjxjzBB0UH+VsGU7vPTHs10WsK\nivvG3dZbVi4HlaRHYORrF3MRqUl7MO0hRYYy/g/7TuRpq2ABcn8vVgQRP0b9\nW/9uSGGyfmAPR0s/2kr7VFpeWTnp29AMsZEkdIRnkI5eJguim7A="
- secure: "KTl0n8tpydS2OpGZOxCgWhlLQZF2x7t+GoNRD83HKIknQAB92YqX0FUpOlk1\nVM/oPJ56ThLVdAmyG19bkrTHYrYKTlOFDOE1WfKSWNQBn/uBYntJ2HWN0t5W\nF+qkGGGeeTSoqBW9MuB+eFHVfcv8ziOUCeQs/Mol+zaXcaGPXRc="
- DB=postgres
- echo $TEST_ENV
- bundle exec cucumber -r features
- bundle exec rspec -f d -c
- RAILS_ENV=test bundle exec rake db:reset
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- RAILS_ENV=test bundle exec rake db:migrate
- mkdir tmp
- mkdir tmp/cache
- phantomjs --version
- echo $TEST_ENV
